-- +goose Up
REVOKE ALL PRIVILEGES ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO spcase_app;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM spcase_app;
GRANT SELECT, INSERT, UPDATE ON TABLE users TO spcase_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE teams TO spcase_app;
GRANT SELECT, INSERT, DELETE ON TABLE team_members TO spcase_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE submissions TO spcase_app;
GRANT SELECT, INSERT, UPDATE ON TABLE evaluations TO spcase_app;
GRANT SELECT, UPDATE ON TABLE evaluation_state TO spcase_app;
GRANT INSERT ON TABLE evaluation_state_events TO spcase_app;

REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM spcase_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO spcase_app;

REVOKE ALL PRIVILEGES ON TYPE user_role FROM PUBLIC;
GRANT USAGE ON TYPE user_role TO spcase_app;

ALTER DEFAULT PRIVILEGES FOR ROLE spcase_migrator IN SCHEMA public
    REVOKE ALL PRIVILEGES ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE spcase_migrator IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO spcase_app;
ALTER DEFAULT PRIVILEGES FOR ROLE spcase_migrator IN SCHEMA public
    REVOKE ALL PRIVILEGES ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE spcase_migrator IN SCHEMA public
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO spcase_app;
ALTER DEFAULT PRIVILEGES FOR ROLE spcase_migrator IN SCHEMA public
    REVOKE ALL PRIVILEGES ON TYPES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE spcase_migrator IN SCHEMA public
    GRANT USAGE ON TYPES TO spcase_app;

-- +goose Down
ALTER DEFAULT PRIVILEGES FOR ROLE spcase_migrator IN SCHEMA public
    REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM spcase_app;
ALTER DEFAULT PRIVILEGES FOR ROLE spcase_migrator IN SCHEMA public
    REVOKE USAGE, SELECT, UPDATE ON SEQUENCES FROM spcase_app;
ALTER DEFAULT PRIVILEGES FOR ROLE spcase_migrator IN SCHEMA public
    REVOKE USAGE ON TYPES FROM spcase_app;

REVOKE USAGE ON TYPE user_role FROM spcase_app;
GRANT USAGE ON TYPE user_role TO PUBLIC;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM spcase_app;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM spcase_app;
REVOKE USAGE ON SCHEMA public FROM spcase_app;
