package middleware

import (
	"net/http"
	"strings"

	"spcase.ru/backend/internal/domain"
)

// APIErrorResponses converts errors generated by the standard router into the
// API error contract. Handler-produced JSON errors pass through unchanged.
func APIErrorResponses(next http.Handler) http.Handler {
	if next == nil {
		panic("API error middleware next handler cannot be nil")
	}

	return http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		if !isAPIV1Path(request.URL.Path) {
			next.ServeHTTP(writer, request)
			return
		}

		next.ServeHTTP(&apiErrorResponseWriter{ResponseWriter: writer}, request)
	})
}

func isAPIV1Path(path string) bool {
	return path == "/api/v1" || strings.HasPrefix(path, "/api/v1/")
}

type apiErrorResponseWriter struct {
	http.ResponseWriter
	wroteHeader bool
	replaced    bool
}

func (writer *apiErrorResponseWriter) WriteHeader(status int) {
	if writer.wroteHeader {
		return
	}
	writer.wroteHeader = true

	if isJSONResponse(writer.Header().Get("Content-Type")) {
		writer.ResponseWriter.WriteHeader(status)
		return
	}

	var domainError *domain.DomainError
	switch status {
	case http.StatusNotFound:
		domainError = domain.ErrRouteNotFound
	case http.StatusMethodNotAllowed:
		domainError = domain.ErrMethodNotAllowed
	default:
		writer.ResponseWriter.WriteHeader(status)
		return
	}

	writer.replaced = true
	writer.Header().Del("Content-Length")
	writeDomainError(writer.ResponseWriter, status, domainError)
}

func (writer *apiErrorResponseWriter) Write(payload []byte) (int, error) {
	if !writer.wroteHeader {
		writer.WriteHeader(http.StatusOK)
	}
	if writer.replaced {
		return len(payload), nil
	}
	return writer.ResponseWriter.Write(payload)
}

// Unwrap lets net/http.ResponseController retain access to the original
// response writer and its optional interfaces.
func (writer *apiErrorResponseWriter) Unwrap() http.ResponseWriter {
	return writer.ResponseWriter
}

func isJSONResponse(contentType string) bool {
	contentType = strings.ToLower(strings.TrimSpace(contentType))
	return contentType == "application/json" || strings.HasPrefix(contentType, "application/json;")
}
